version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file:
      - .env
  ghi:
    build:
      context: ./ghi
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./ghi:/app
      - /app/node_modules
